### ISSUE TITLE
Printing large image cause delay

### ISSUE THREAD

**Issue by nikunjflobiz** [DantSu/ESCPOS-ThermalPrinter-Android#183]
@DantSu   I am trying to print a large image splitting with a height of 255 px of each while printing there is a slide delay after every 256 px of height?  If I change the height to 1024 px, it works fine with less number of delay.
Do you recommend this solution?  Can it cause any damage?

**Comment by DantSu** [comment]
If you have a good printer with a good cache memory and speed print, keep 1024. With some chinese printers with low cache or some bluetooth connection, image too big cause error due to too many data send at the same time.
If you work only with one printer model, fork and change the code has you want.

**Comment by nikunjflobiz** [comment]
Thanks for the quick help
