### ISSUE TITLE
Print arabic

### ISSUE THREAD

**Issue by mrsaedsadi** [DantSu/ESCPOS-ThermalPrinter-Android#448]
Can not print Arabic characters .

**Comment by ibnzahoor98** [comment]
In order to print arabic, please do the following things:
**Step 01:** 
`EscPosPrinter printer = new EscPosPrinter(deviceConnection, 203, 48f, 32, new EscPosCharsetEncoding("windows-1252", 16));`

Add this argument in EscPosPrinter constructor 
**new EscPosCharsetEncoding("windows-1252", 16)**

**Step 02:**
Now question is what is **`windows-1252`** and **`16`** that is passed as argument in **`EscPosCharsetEncoding`** constructor. Replace **`windows-1252`** with **`UTF-8`** and digit **`16`** with **`32`**.

Why 32? 32 is **`escPosCharsetId`** and it represents  **`[PC720: Arabic]`** for more info you can read this
https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=32

**Step 03:**
Write below code

`EscPosPrinter printer = new EscPosPrinter(deviceConnection, 203, 48f, 32, new EscPosCharsetEncoding("UTF-8", 32));`

**Step 04:**
Now open your android. **`Go to settings`** -> **`search for printer settings`** -> **`change encoding to UTF-8`**

**Comment by DantSu** [comment]
Thx @ibnzahoor98 for your reply. 

@mrsaedsadi As we don't know which printer you use because you don't know how write issue correctly.... `escPosCharsetId` is not the same for all printer. For you, is may be not 32 because you may use a printer of other brand. You have to find by yourself.
