### ISSUE TITLE
QRCode is not allowing large strings

### ISSUE THREAD

**Issue by MrDanSB** [DantSu/ESCPOS-ThermalPrinter-Android#461]
Hi, good day.

I'm trying to generate a QR Code that has an URL coming from server, but I notice something:

If I set the size to 25, the QR Code prints fine but I can't scan it. (I can scan it if a put short URL's like https://www.google.com)

<blockquote class="imgur-embed-pub" lang="en" data-id="2MQTecN"><a href="https://imgur.com/2MQTecN">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

If I increase the size of the QR Code to 35, the printer fails to print the image.

<blockquote class="imgur-embed-pub" lang="en" data-id="q1aAS4Q"><a href="https://imgur.com/q1aAS4Q">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

My URL size that I need to use is like 400 characters or more... 

Can anyone help me?

**Comment by herdumundo** [comment]
I have the same issue

**Comment by DantSu** [comment]
400 characters is too long, you need too many space to print it. Paper size is 2 inch, 203 dpi in most case, so 406 points width. If you want to print a QRCode like this it will be unreadable due to the printer definition limitation.

![image](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/4188774/c7e11350-7c6b-4b57-8d34-d812675db5ac)
