### ISSUE TITLE
QR Code print speed issue

### ISSUE THREAD

**Issue by onuryurtturk** [DantSu/ESCPOS-ThermalPrinter-Android#72]
Hi, in some cases, I could not get the exact condition. QR Code printing is very slow (waiting and in 5 seconds in total), sometimes it prints in a single second. Do you have any comments on that?

**Comment by DantSu** [comment]
You use a bluetooth connection, right ?
My printer do the same thing in bluetooth mode, but when I use USB that never happen. So, I think that many data are lost and resend, and the connection is broken and then reestablished... The bluetooth stability  is not the most reliable.

**Comment by onuryurtturk** [comment]
Yes I'm using bluetooth connection. I haven't tried usb either because we won't use it with usb. So is there a way to prevent this? When I changed the print quality and speed, there was no change. Suddenly slow writing may occur at the time of T.

**Comment by onuryurtturk** [comment]
Hello again,Is there a way to prevent this? or are there any documents we can review? We have a large number of users and if we encounter this error in the field, we cannot explain it that way. Therefore, we want to take precautions from the very beginning.

**Comment by DantSu** [comment]
For a maximum compatibilité with ESC printers. I print QR code as an image.
But it's exist a command that not commonly compatible wich print QR code.
I can't test it because my printer is not compatible with QR Code command.

You can update this class : 
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/escposprinter/src/main/java/com/dantsu/escposprinter/textparser/PrinterTextParserQRCode.java
if you implements directly  `implements IPrinterTextParserElement` and change methods like this : 
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/escposprinter/src/main/java/com/dantsu/escposprinter/textparser/PrinterTextParserString.java
You can't solved your problem !

Here is a method that I try to develop with no success with my printer : 
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/139fca50e2a8fedf3f521edc03212edf88ec1005/escposprinter/src/main/java/com/dantsu/escposprinter/EscPosPrinterCommands.java#L360
